/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/HomePage/Posters.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Posters = (props) => {
  const { nodes, materials } = useGLTF('/Models/HomePage//Posters.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[3, 0, 0]} rotation={[1.57, 0, 0]}>
        <mesh geometry={nodes['imagination-loa-1_360x_1'].geometry} material={materials['imagination-loa-1_360x']} />
        <mesh geometry={nodes['imagination-loa-1_360x_2'].geometry} material={materials['iceland-2-1_360x']} />
        <mesh geometry={nodes['imagination-loa-1_360x_3'].geometry} material={materials['under-korsbarstradet-host-1_360x']} />
        <mesh geometry={nodes['imagination-loa-1_360x_4'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['imagination-loa-1_360x_5'].geometry} material={materials['dalahast-if-1_360x']} />
        <mesh geometry={nodes['imagination-loa-1_360x_6'].geometry} material={materials['grass-by-the-lake-1_360x']} />
        <mesh geometry={nodes['imagination-loa-1_360x_7'].geometry} material={materials['the-mountain-1_360x']} />
      </group>
    </group>
  )
}

export default Posters

useGLTF.preload('/Models/HomePagePosters.gltf')
